### ISSUE TITLE
Non-nullable parameter on a nullable parameter

### ISSUE THREAD

**Issue by atoennis** [atomicrobot/Carbon-Android#62]
Parameter `recoveryIntent` should be nullable at https://github.com/atomicrobot/android-starter-project/blob/1538eb441a9da202a7cd1a600caafa625e16400b/app/src/main/java/com/mycompany/myapp/app/BaseApplicationInitializer.kt#L32

Per the [docs](https://developers.google.com/android/reference/com/google/android/gms/security/ProviderInstaller.ProviderInstallListener)

> if non-null, an intent that can be used to install or update Google Play Services such that the provider can be installed

Sample crash with package name obfuscated:
```
Fatal Exception: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method b.d.b.f.b, parameter recoveryIntent
       at com._._.app.BaseApplicationInitializer$upgradeSecurityProvider$1.onProviderInstalled(Unknown Source)
       at com.google.android.gms.security.zza.onPostExecute(Unknown Source)
       at android.os.AsyncTask.finish(AsyncTask.java:636)
       at android.os.AsyncTask.access$500(AsyncTask.java:177)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5263)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by ascheetz** [comment]
`recoveryIntent` is now nullable
